name: Build and Push Purescript-Tools image

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build and push purescript-tools
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4
        with:
          images: |
            ghcr.io/flipstone/purescript-tools
          tags: |
            type=sha,format=short,prefix=debian-stable-purescript-0.15.12-{{ date 'YYYY-MM-DD' }}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build, tag, and push image to GCR
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha,mode=max,ignore-error=true
          cache-to: type=gha,mode=max,ignore-error=true
          platforms: 'linux/amd64, linux/arm64'
          provenance: false
